# Gitee Go CI/CD 配置文件
# 使用 Gitee Go 流水线语法

version: "1.0"

stages:
  - install
  - test
  - build

variables:
  PIP_INDEX_URL: "https://pypi.tuna.tsinghua.edu.cn/simple"

# 安装依赖
install:
  stage: install
  image: python:3.9-slim
  script:
    - apt-get update && apt-get install -y --no-install-recommends gcc g++ make libgomp1
    - pip install --upgrade pip -i $PIP_INDEX_URL
    - pip install numpy==1.24.3 pandas==2.0.3 -i $PIP_INDEX_URL
    - pip install -r requirements.txt -i $PIP_INDEX_URL
    - echo "Dependencies installed successfully"
    - python main.py
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - /root/.cache/pip

# 单元测试
run_unit_tests:
  stage: test
  image: python:3.9-slim
  needs:
    - install
  script:
    - apt-get update && apt-get install -y --no-install-recommends gcc g++ make libgomp1
    - pip install --upgrade pip -i $PIP_INDEX_URL
    - pip install numpy==1.24.3 pandas==2.0.3 -i $PIP_INDEX_URL
    - pip install -r requirements.txt -i $PIP_INDEX_URL
    - cd pro2
    - echo "========================================"
    - echo "Running UNIT TESTS"
    - echo "========================================"
    - python -m pytest tests/unit -v --tb=short --html=tests/reports/unit_test_report.html --self-contained-html 2>&1 | tee tests/reports/unit_test_log.txt || echo "Unit tests completed with some failures"
  artifacts:
    when: always
    paths:
      - pro2/tests/reports/

# 集成测试
run_integration_tests:
  stage: test
  image: python:3.9-slim
  needs:
    - install
  script:
    - apt-get update && apt-get install -y --no-install-recommends gcc g++ make libgomp1
    - pip install --upgrade pip -i $PIP_INDEX_URL
    - pip install numpy==1.24.3 pandas==2.0.3 -i $PIP_INDEX_URL
    - pip install -r requirements.txt -i $PIP_INDEX_URL
    - cd pro2
    - echo "========================================"
    - echo "Running INTEGRATION TESTS"
    - echo "========================================"
    - python -m pytest tests/integration -v --tb=short --html=tests/reports/integration_test_report.html --self-contained-html 2>&1 | tee tests/reports/integration_test_log.txt || echo "Integration tests completed with some failures"
  artifacts:
    when: always
    paths:
      - pro2/tests/reports/

# 执行所有测试
run_all_tests:
  stage: test
  image: python:3.9-slim
  needs:
    - install
  script:
    - apt-get update && apt-get install -y --no-install-recommends gcc g++ make libgomp1
    - pip install --upgrade pip -i $PIP_INDEX_URL
    - pip install numpy==1.24.3 pandas==2.0.3 -i $PIP_INDEX_URL
    - pip install -r requirements.txt -i $PIP_INDEX_URL
    - pip install pytest-cov -i $PIP_INDEX_URL
    - cd pro2
    - echo "========================================"
    - echo "Running ALL TESTS"
    - echo "========================================"
    - python -m pytest tests/ -v --tb=short --cov=fund_search --cov-report=xml --cov-report=html --html=tests/reports/all_tests_report.html --self-contained-html 2>&1 | tee tests/reports/all_tests_log.txt || echo "All tests completed with some failures"
    - echo ""
    - echo "Test Summary:"
    - python -m pytest tests/ --co -q 2>/dev/null | tail -5 || echo "Could not generate summary"
  artifacts:
    when: always
    paths:
      - pro2/tests/reports/
      - pro2/htmlcov/
      - pro2/coverage.xml

# 代码风格检查
lint:
  stage: test
  image: python:3.9-slim
  needs:
    - install
  script:
    - pip install flake8 -i $PIP_INDEX_URL
    - cd pro2
    - echo "Running lint check..."
    - flake8 fund_search --count --select=E9,F63,F7,F82 --show-source --statistics || true
  allow_failure: true

# 构建
build:
  stage: build
  image: python:3.9-slim
  needs:
    - install
    - run_unit_tests
    - run_integration_tests
    - run_all_tests
  script:
    - apt-get update && apt-get install -y --no-install-recommends gcc g++ make libgomp1
    - pip install --upgrade pip -i $PIP_INDEX_URL
    - pip install numpy==1.24.3 pandas==2.0.3 -i $PIP_INDEX_URL
    - pip install -r requirements.txt -i $PIP_INDEX_URL
    - echo "========================================"
    - echo "BUILD SUCCESSFUL"
    - echo "========================================"
    - python main.py
    - echo ""
    - echo "Test reports available in:"
    - ls -la pro2/tests/reports/ 2>/dev/null || echo "No reports found"
  only:
    - master
    - develop
