# Gitee CI/CD 配置文件
# 参考文档: https://gitee.com/help/articles/4113

stages:
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # 使用 SQLite 进行测试，避免 MySQL 依赖问题
  USE_SQLITE: "true"
  # 设置工作目录
  WORK_DIR: "pro2"

# 缓存配置
cache:
  paths:
    - .cache/pip
    - venv/

# 单元测试任务
unit_test:
  stage: test
  image: python:3.10-slim
  before_script:
    # 安装系统依赖
    - apt-get update && apt-get install -y gcc pkg-config
    # 创建虚拟环境
    - python -m venv venv
    - source venv/bin/activate
    # 升级 pip
    - pip install --upgrade pip
    # 安装项目依赖
    - pip install -r requirements.txt
    # 进入工作目录
    - cd $WORK_DIR
  script:
    # 运行单元测试（跳过数据库测试）
    - pytest tests/unit -v --cov=fund_search --cov-report=xml --cov-report=html --html=tests/reports/unit_test_report.html --self-contained-html -k "not database"
  artifacts:
    when: always
    paths:
      - pro2/tests/reports/
      - pro2/htmlcov/
      - pro2/coverage.xml
    expire_in: 1 week
  coverage: '/TOTAL.*\s+(\d+%)$/'

# 集成测试任务（API测试）
api_test:
  stage: test
  image: python:3.10-slim
  before_script:
    - apt-get update && apt-get install -y gcc pkg-config
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - cd $WORK_DIR
  script:
    # 运行 API 集成测试
    - pytest tests/integration/test_api.py -v --html=tests/reports/api_test_report.html --self-contained-html
  artifacts:
    when: always
    paths:
      - pro2/tests/reports/
    expire_in: 1 week

# 代码质量检查
lint:
  stage: test
  image: python:3.10-slim
  before_script:
    - pip install flake8 pylint
    - cd $WORK_DIR
  script:
    # 检查代码风格
    - flake8 fund_search --count --select=E9,F63,F7,F82 --show-source --statistics || true
    - pylint fund_search --disable=all --enable=E,F || true
  allow_failure: true

# 构建任务
build:
  stage: build
  image: python:3.10-slim
  dependencies:
    - unit_test
  before_script:
    - apt-get update && apt-get install -y gcc pkg-config
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - cd $WORK_DIR
  script:
    - echo "Build successful!"
    - echo "Application is ready for deployment"
  artifacts:
    paths:
      - pro2/fund_search/
    expire_in: 1 week
  only:
    - master
    - develop
