from .advanced_strategies import BaseStrategy, get_all_advanced_strategies
from .builtin_strategies import BuiltinStrategies, get_builtin_strategies_manager
from .custom_strategy_backtest import CustomStrategyBacktest, BacktestResult, TradeRecord, run_custom_backtest
from .enhanced_strategy import EnhancedInvestmentStrategy
from .ml_prediction_strategy import MLPredictionStrategy
from .strategy_adapter import StrategyAdapter, get_strategy_adapter
from .strategy_selector import StrategySelector, get_strategy_selector
from .trend_analyzer import TrendAnalyzer, TrendType, TrendResult
